services:
  - type: web
    name: jobillo
    env: node
    buildCommand: npm install && npm run setup-models && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000